# docker-compose for development setup
version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  db-test:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db

  api:
    container_name: pruebas-apis
    image: davidgk/pruebas-apis
    networks:
      - internal_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4500:4500
    volumes:
      - ./api:/server:delegated
    depends_on:
      - db
    command: sh -c "npm install && npm run build && npm run start" # git install succeeds even though an error is thrown so unconditionally run the next command
volumes:
  mongodb:

networks:
  internal_api:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
